add research notes file
brittanyjoiner15/eui-event-template pull request #45
Opened 2022-09-28 16:40 UTC by Mannuel25

#### Describe your changes
I added a research notes markdown file to keep track of all researches made.
#### Link to issue this resolves
Fixes: #42 

- [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
- [x] This **description** should include ...
  - [x] A short summary of your changes
  - [x] A link to the issue that relates to these changes
  - [ ] A screenshot of the changes if possible!
- [x] Add `brittanyjoiner15` as a reviewer
- [x] Add yourself as assignee

2022-09-28 16:41 UTC, Mannuel25 commented
I made researches as regards a format that'd fit in for such a file like this. Unfortunately, I couldn't find one, so i thought of a format and constructed the markdown file. 

Kindly let me know if the format is okay, or requires necessary corrections. Thanks.

2022-09-28 16:46 UTC, brittanyjoiner15 requested changes
Just a quick nitpick to change the wording, but i think this does work! If you can fix that in the text, I think this is good to go!

2022-09-28 16:46 UTC, brittanyjoiner15 commented on docs/research-notes.md
> +#### This file includes research done to assist improve the app, including suggestions for new features or technologies.
```suggestion
#### This file includes research done to improve the app, including suggestions for new features or technologies.
```

2022-09-28 17:09 UTC, Mannuel25 commented on docs/research-notes.md
> +#### This file includes research done to assist improve the app, including suggestions for new features or technologies.
Fixed.

2022-09-28 17:15 UTC, brittanyjoiner15 approved these changes
Looks good! I'll merge this on the 1st!

2022-09-28 17:15 UTC, Mannuel25 commented
> Looks good! I'll merge this on the 1st!

Thank you!

2022-10-01 15:56 UTC, brittanyjoiner15 commented
@Mannuel25 merging this now!

2022-10-01 15:57 UTC, merged

2022-10-01 16:02 UTC, Mannuel25 commented
> @Mannuel25 merging this now!

Thank you 😊