Update Customization Guide
brittanyjoiner15/eui-event-template pull request #48
Opened 2022-09-29 22:15 UTC by shahx95

#### Describe your changes

Created a customization checklist that lists down the changes any user would have to make if they plan to use the template for their own event. This checklist guide contains changes that need to be made in the nav bar, the event details section, the talks section, and the bottom bar. Each change also carries a brief instruction on how to implement the change.

#### Link to issue this resolves

https://github.com/brittanyjoiner15/eui-event-template/issues/21

#### Screenshot of changes(if relevant)

- [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
- [x] This **description** should include ...
  - [x] A short summary of your changes
  - [x] A link to the issue that relates to these changes
  - [ ] A screenshot of the changes if possible!
- [x] Add `brittanyjoiner15` as a reviewer
- [x] Add yourself as assignee

2022-09-30 00:33 UTC, brittanyjoiner15 requested changes
Overall this is awesome and really close! Added a couple comments, and when you reference things like _line 12_, let's change that for now because those line numbers could change. Instad if we can reference a permalink to the code that would be great. Like this
---

- [ ] ** Change logo text:** Go to the [`rainbowLetters.jsx` file](https://github.com/brittanyjoiner15/eui-event-template/blob/8cefe4c73b1dea7f5fa33c6bd15071cb1bbae463/src/utilities/rainbowLetters.jsx#L27) and replace `"{rainbowedLetters} SUMMIT" with the name of your event.

----
If you can make those changes to the places where you reference lines, i think that would be cleaner and easier to reference! But overall this looks great!

2022-09-30 00:33 UTC, brittanyjoiner15 commented on docs/customization_checklist.md
> +- [ ] **Change logo and favicon:** Follow the path ```eui-event-template/src/data/consts.js```. In the ```const.js``` file, on _line 12_, replace the placeholder rainbow cluster link with a link of y
What do you think about leaving a permalink here to reference that line? Reference this link: 
https://github.com/brittanyjoiner15/eui-event-template/blob/8cefe4c73b1dea7f5fa33c6bd15071cb1bbae463/src/data/consts.js#L12

2022-09-30 00:33 UTC, brittanyjoiner15 commented on docs/customization_checklist.md
> +- [ ] **Change speaker layout:** This is an optional change. Depending on the number of speakers in your event, you may want to change the layout of the speakers section. Follow the path ```eui-event
This is a good point! Great job including that!

2022-09-30 00:33 UTC, brittanyjoiner15 commented on docs/customization_checklist.md
> +
Might want to add another `### Speaker` header here like you did for Event Details and Talks sections

2022-09-30 00:33 UTC, brittanyjoiner15 commented on docs/customization_checklist.md
> +- [ ] **Change schedule**: Follow the path ```eui-event-template/src/data/talks.js```. In the ```talks.js``` file, there is a _talks array (line 7)_ holding each individual talk as an object. Each ob
Good callout about the GMT time!

2022-10-02 22:02 UTC, brittanyjoiner15 commented
@shahx95 hey just wanted to check in on this and see if you had a chance to make the requested changes?

2022-10-03 16:45 UTC, shahx95 commented
> @shahx95 hey just wanted to check in on this and see if you had a chance to make the requested changes?

Hi @brittanyjoiner15. I'll be on it today

2022-10-03 18:04 UTC, shahx95 commented
Hey @brittanyjoiner15. I have made the requested changes 😊

2022-10-05 01:51 UTC, brittanyjoiner15 approved these changes
This all looks great! Thanks for making those changes!

2022-10-05 01:51 UTC, merged