Sign Up feature added successfully to the same google sheet
brittanyjoiner15/eui-event-template pull request #72
Opened 2022-10-03 18:43 UTC by SahilAnower

#### Changes
> Added the feature to add new user to the same spreadsheet.

#### Link to issue this resolves
> #36 

#### Screenshot of changes(if relevant)

* [x] Added and updated documentation for someone to add user to the spreadsheet. Also utilities env link, I have changed to new deployed one, where speaker logic and signup user lives together. And also converted React class based component to functional based in Bottombar.jsx, hope that won't be an issue. :slightly_smiling_face:
* [x] Reviewer - brittanyjoiner15 
* [x] Assignee - Me

> Looking for some Improvements and do tell if any faults herein. :handshake:🏻

2022-10-05 01:24 UTC, brittanyjoiner15 commented on src/components/BottomBar.jsx
> +  const validateEmailName = (email, name) => {
This is awesome!! Very proactive thinking here, I love it

2022-10-05 01:41 UTC, brittanyjoiner15 requested changes
Few minor changes that should hopefully be really quick to fix, then I'll be happy to merge. This is amazing and vastly improves the functionality of the app!! Thank you so much!!

2022-10-05 01:41 UTC, brittanyjoiner15 commented on src/components/BottomBar.jsx
> +  const validateEmailName = (email, name) => {
@SahilAnower  i love this error handling, and this might be a very edge case, but we might want to update it to validate on blur or on change, because if you type and meet the criteria, but then backspace and don't meet the criteria, the button still looks clickable, but it doesn't actually submit and just kinda sits there and disables the submit button

![Kapture 2022-10-05 at 02 30 26](https://user-images.githubusercontent.com/16166290/193960184-9ac87d1e-a1d4-415d-951d-a2f47ac7075d.gif)

So maybe can you either check on blur so that no one clicks the button unless both inputs are actually valid? 

I also might possibly break this out into two separate functions - one to check name and one to check email, and then onBlur for each field, you can check if the respective field is valid.

2022-10-05 01:41 UTC, brittanyjoiner15 commented on README.md
> +#### 2. For Speakers Sheet - Add name, title, team, location, shortBio, pronouns, imageLink headers in the sheet. For Sign Up Sheet - Add name and email headers (make sure the order of headers is sam
Thanks for clarifying and updating this!

2022-10-05 01:41 UTC, brittanyjoiner15 commented on src/components/BottomBar.jsx
> +      text: <p>Thanks for subscribing to us!</p>,
Let's make this text `Thanks for registering!`

2022-10-05 01:41 UTC, brittanyjoiner15 commented on src/components/BottomBar.jsx
> +    errors = ["Enter Valid Name", "Enter Valid Email"];
I see the error messages here, but im not seeing them appear in the app. I think that's because you'll need to pass the `isInvalid` prop to the respective form row with the result of the validation function. Check out these Eui docs: https://elastic.github.io/eui/#/forms/form-validation

2022-10-05 01:41 UTC, brittanyjoiner15 commented on src/components/BottomBar.jsx
> +            Send Details 🙌🏻
I love the emoji! Can we change `Send Details` to `Save My Spot` ?

2022-10-05 06:38 UTC, SahilAnower commented on src/components/BottomBar.jsx
> +  const validateEmailName = (email, name) => {
Yeah I am changing this, and then would reflect back!

2022-10-05 06:38 UTC, SahilAnower commented on src/components/BottomBar.jsx
> +            Send Details 🙌🏻
Yeah Sure

2022-10-05 19:18 UTC, SahilAnower commented
Hey @brittanyjoiner15 , Can you please check it once. I improved some things. Do tell me if any thing goes unexpected! 😊

2022-10-06 04:24 UTC, brittanyjoiner15 commented
@SahilAnower confirming I've seen your comment and just didn't get a chance to look today but will look tomorrow!

2022-10-06 04:38 UTC, brittanyjoiner15 commented
@SahilAnower actually just got a chance to look, and i think this is good! I'm still not able to see the error messages, but i think for now the button disabling and re-enabling at the right time is clear enough. Can you fix the merge conflicts in `BottomBar` and then I'll run once more and confirm all is good, and then merge this?

2022-10-06 05:39 UTC, SahilAnower commented
> @SahilAnower actually just got a chance to look, and i think this is good! I'm still not able to see the error messages, but i think for now the button disabling and re-enabling at the right time is clear enough. Can you fix the merge conflicts in `BottomBar` and then I'll run once more and confirm all is good, and then merge this?

Yeah I just resolved them. Can you check once?

2022-10-07 16:37 UTC, brittanyjoiner15 commented
@SahilAnower im so sorry for the delay on this! can you check the merge conflicts once more? I would go and change them myself but we just also merged in some changes for the google script for render the talks, so i want to make sure this doesn't break anything to be able to do both. - which URL do we need for the web app? 

And as far as readme - i just want to make sure i don't screw up the docs for incorporating how to both relay info from speakers and talks and also capture signups.

2022-10-07 16:41 UTC, SahilAnower commented
Hey @brittanyjoiner15 , I resolved the merge conflicts, can you please check?

2022-10-07 16:44 UTC, SahilAnower commented
> @SahilAnower im so sorry for the delay on this! can you check the merge conflicts once more? I would go and change them myself but we just also merged in some changes for the google script for render the talks, so i want to make sure this doesn't break anything to be able to do both. - which URL do we need for the web app?
> 
> And as far as readme - i just want to make sure i don't screw up the docs for incorporating how to both relay info from speakers and talks and also capture signups.

Okay Confirming once, please hold on.

2022-10-07 17:02 UTC, SahilAnower commented
Yeah Resolved them. It's okay now. Working fine from npm start at my end.

2022-10-08 18:06 UTC, brittanyjoiner15 commented
@SahilAnower perfect! looks great, thanks so much for your work on this!!

2022-10-08 18:07 UTC, merged